AllCops:

  Exclude:

    - spec/*

    - tasks/*

    - Rakefile

    - Gemfile

    - "*.gemspec"

# for disabling the 'Missing magic comment # frozen_string_literal: true' warmning. 
Style/FrozenStringLiteralComment:
  Enabled: false

# for disabling extra space warning
Layout/ExtraSpacing:
  Enabled: false

# for disabling 'Final new line missing' warning.
Layout/TrailingBlankLines:
  Enabled: false

# for disabling 'Carriage return character missing.' warning
Layout/EndOfLine:
  Enabled: false

# for disabling the use snake_case for variable
Naming/VariableName:
  Enabled: false

# for disabling ' %w-literals should be delimited by [ and ].' warning
Style/PercentLiteralDelimiters:
  Enabled: false

# for disabling the warning about 'Only use lowercase characters for block parameter'
Naming/UncommunicativeBlockParamName:
  Enabled: false

# for disabling the warning about - 'The closing array brace must be on the same line as the last array element when the opening brace is on the same line as the first array element'
Layout/MultilineArrayBraceLayout:
  Enabled: false

# set maximum length for block
Metrics/BlockLength:
  Max: 500

# for disabling the warning about - 'Space missing inside the block braces'
Layout/SpaceInsideBlockBraces:
  Enabled: false

# set maximum length for Line
Metrics/LineLength:
  Max: 500

# remove extra space line warning
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# remove warning about Prefer single-quoted strings when you don't need string interpolation or special symbols.
Style/StringLiterals:
  Enabled: false

# set minimum length for method parameter
Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

# disable Class length warning
Metrics/ClassLength:
  Enabled: false

# disable 'Missing space after #' for comment
Layout/LeadingCommentSpace:
  Enabled: false

# do not assign mutable objects to constant,- Disable the warning about Freeze mutable objects assigned to constants.
Style/MutableConstant:
  Enabled: false

# set the maximum method length
Metrics/MethodLength:
  Max: 40

# disabled warning - 'should be surrounded by a single space'
Layout/SpaceAroundOperators:
  Enabled: false

# disable warning about tab
Layout/Tab:
  Enabled: false

#  Unnecessary disabling of Metrics/MethodLength
Lint/UnneededCopDisableDirective:
  Enabled: false

# Disable the warning about - gem shoul be in alphabetical order
Bundler/OrderedGems:
  Enabled: false

# disable warning about trailing whitespaces
Layout/TrailingWhitespace:
  Enabled: false

# disable warning about 'Checks style of how access modifiers are used'
Style/AccessModifierDeclarations:
  Enabled: false

# disable warning about extra line added in code
Layout/EmptyLines:
  Enabled: false

# disable warning about  'Checks for a `# rubocop:enable` after `# rubocop:disable`.'
Lint/MissingCopEnableDirective:
  Enabled: false

# disbale warning about 'Add empty line after guard clause.'
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# disable warning about 'top level class documentation comment'
Style/Documentation:
  Enabled: false

# disable warning about 'Use the new Ruby 1.9 has syntax '
Style/HashSyntax:
  Enabled: false

# disable warning about duplicate case
Lint/DuplicateCaseCondition:
  Enabled: false

# disable warning about same line comment
Style/CommentedKeyword:
  Enabled: false

# diable warning about Indentation width
Layout/IndentationWidth:
  Enabled: false

# disable warning about Block alignment
Layout/BlockAlignment:
  Enabled: false

# diable warning about Check the naming of accessor methods for get_/set_
Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: false