include:
  - project: kount/third_party/tpa-ci-shared
    file: 
      - base/sq-scan.yml
      - version.yml
      - core/rules.yml
    ref: 2.16.0

stages:
  - version
  - test
  - sonarqube scan
  - lint
  - build and deploy

.ruby:
  image: ruby:3.0
  before_script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install
    - mkdir ~/.gem
    - echo "---" > ~/.gem/credentials
    - curl -u $RUBYGEMS_USERNAME:$RUBYGEMS_PASSWORD  https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - echo BUILD_VERSION=${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}
    - |
      if [ -n "${BUILD_VERSION}" ]
      then
        BUILD_VERSION=`echo $BUILD_VERSION | cut -c-17`
        # BUILD_VERSION is cut to 17 characters so SDK_VERSION will not exceed 32 characters in total
        echo "sed -i \"s/0.0.0/${BUILD_VERSION}/g\" ${CI_PROJECT_DIR}/lib/kount/config.rb"
        sed -i "s/0.0.0/${BUILD_VERSION}/g" ${CI_PROJECT_DIR}/lib/kount/config.rb
      fi

test:
  stage: test
  extends: .ruby
  script:
    - bundle exec rake test
    - ruby -rjson -e 'sqube = JSON.load(File.read("coverage/.resultset.json"))["RSpec"]["coverage"].transform_values {|lines| lines["lines"]}; total = { "RSpec" => { "coverage" => sqube, "timestamp" => Time.now.to_i }}; puts JSON.dump(total)' > coverage/.resultset.sq.json
  rules:
    - !reference [.rule-on-tag]
    - !reference [.rule-on-master]
    - !reference [.rule-on-mr]
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/coverage/.resultset.sq.json

sonarqube scan:
  extends: .sq-scan
  stage: sonarqube scan
  variables:
    SRC_EXCLUSIONS: "**/build/**,**/spec/**,**/vendor/**,**/DS_Store/**,**/idea/**,**/*LICENSE,**/*.gitignore,**/*.yml,**/*.lock"
    RUBY_TEST_COVERAGE_REPORT_PATHS: "${CI_PROJECT_DIR}/coverage/.resultset.sq.json"
    
# The purpose of Below test stage is to approve merger request (As It's mentioned in required approval - pipeline need to be pass for approve the Merge request)
lint:
  stage: lint
  extends: .ruby
  rules:
    - !reference [.rule-on-tag]
    - !reference [.rule-on-master]
    - !reference [.rule-on-mr]
  script:
    - rubocop



build and deploy:
  stage: build and deploy
  extends: .ruby
  rules: 
    - !reference [.rule-on-tag]
  script:
    - bash gem_build.sh
  artifacts:
    paths:
      - "*.gem"

